[workspace]
resolver = "3"
members = ["spacemit-riscv"]
default-members = ["spacemit-riscv"]

[workspace.package]
edition = "2024"
license = "MulanPSL-2.0 OR MIT"
repository = "https://atomgit.com/rustsbi/spacemit-hal"

[workspace.dependencies]
riscv = { version = "0.16.1", default-features = false }

[profile.release]
debug = true
