[package]
name = "spacemit-hal"
description = "SpacemiT SoC driver support"
version = "0.0.0"
documentation = "https://docs.rs/spacemit-hal"
edition.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
keywords = ["hal", "riscv", "spacemit", "k1", "k3"]
categories = ["os", "embedded", "hardware-support", "no-std"]

[package.metadata.docs.rs]
default-target = "riscv64imac-unknown-none-elf"
targets = ["riscv64imac-unknown-none-elf"]

[dependencies]
embedded-hal = { workspace = true }
embedded-io = { workspace = true }
uart16550 = { workspace = true }
vcell = { workspace = true }
volatile-register = { workspace = true }
