[package]
name = "rot-bootloader"
version = "0.0.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
default-run = "rot-bootloader"

[dependencies]
eeprom24x = "0.7.2"
embedded-hal.workspace = true
embedded-io.workspace = true
measurements.workspace = true
riscv.workspace = true
rot-bootloader-macros = { path = "macros" }
spacemit-hal.workspace = true
spacemit-p1.workspace = true
spacemit-rt.workspace = true
spin = { version = "0.9.9", default-features = false, features = ["once", "spin_mutex"] }

[features]
default = ["spacemit-rt/k1-bootrom"]

[[bin]]
name = "rot-bootloader"
test = false
bench = false

[[bin]]
name = "hello-world"
test = false
bench = false

[[bin]]
name = "eeprom-info"
test = false
bench = false
